// This file is automatically generated. Do not edit it directly.

// Use the browser local storage for a plain local deployment.
export function brokeredPreviewStorage() {
  if (typeof window === 'undefined') return undefined;
  return localStorage;
}
